#!/bin/bash
# ==============================================================================
# ADflow Turb-Calibration: One-Click HPC Deployment Script
# ==============================================================================
#
# Usage:
#   1. Clone this repo to your HPC (or transfer via scp)
#   2. Ensure GCC gfortran + OpenMPI are available (module load)
#   3. Build dependencies (if not already installed):
#      bash hpc/build_deps.sh
#   4. Set PETSC_DIR and CGNS_HOME, then run:
#      bash hpc/deploy.sh
#
# ==============================================================================

set -e

# ======================== USER CONFIGURATION =================================
# Modify these paths to match your HPC environment

# Where to install ADflow (this repo's root)
ADFLOW_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Compiler paths (use absolute paths to avoid conda conflicts)
export MPI_FORT="${MPI_FORT:-mpifort}"
export MPI_CC="${MPI_CC:-mpicc}"

# PETSc installation directory (must contain lib/petsc/conf/variables)
# Auto-detect from build_deps.sh output if not set
if [ -z "$PETSC_DIR" ] && [ -f "$ADFLOW_ROOT/deps/install/petsc/lib/petsc/conf/variables" ]; then
    export PETSC_DIR="$ADFLOW_ROOT/deps/install/petsc"
    echo "  Auto-detected PETSC_DIR from deps/install/"
fi
export PETSC_DIR="${PETSC_DIR:?ERROR: Set PETSC_DIR or run 'bash hpc/build_deps.sh' first}"
export PETSC_ARCH=""

# CGNS installation directory (must contain include/cgnslib.h and lib/libcgns.a)
# Auto-detect from build_deps.sh output if not set
if [ -z "$CGNS_HOME" ] && [ -f "$ADFLOW_ROOT/deps/install/cgns/include/cgnslib.h" ]; then
    export CGNS_HOME="$ADFLOW_ROOT/deps/install/cgns"
    echo "  Auto-detected CGNS_HOME from deps/install/"
fi
export CGNS_HOME="${CGNS_HOME:?ERROR: Set CGNS_HOME or run 'bash hpc/build_deps.sh' first}"

# Python (must have numpy, mpi4py installed)
export PYTHON="${PYTHON:-python3}"

# ======================== AUTOMATIC STEPS ====================================

echo "======================================================================"
echo "  ADflow Turb-Calibration: HPC Deployment"
echo "======================================================================"
echo "  ADFLOW_ROOT: $ADFLOW_ROOT"
echo "  PETSC_DIR:   $PETSC_DIR"
echo "  CGNS_HOME:   $CGNS_HOME"
echo "  MPI_FORT:    $MPI_FORT"
echo "  MPI_CC:      $MPI_CC"
echo "  PYTHON:      $PYTHON"
echo "======================================================================"

# --- Step 1: Generate config.mk ---
echo ""
echo "[1/5] Generating config/config.mk..."

cat > "$ADFLOW_ROOT/config/config.mk" << CONFIGEOF
# Auto-generated by hpc/deploy.sh
PMAKE = make -j 8

FF90 = $MPI_FORT
CC   = $MPI_CC

FF90_INTEGER_PRECISION_FLAG =
FF90_REAL_PRECISION_FLAG    =
CC_INTEGER_PRECISION_FLAG   =
CC_REAL_PRECISION_FLAG      =

CGNS_INCLUDE_FLAGS=-I\$(CGNS_HOME)/include
CGNS_LINKER_FLAGS=-L\$(CGNS_HOME)/lib -lcgns

FF77_FLAGS = -fPIC -fdefault-real-8 -fdefault-double-8 -g -O2 -fallow-argument-mismatch
FF90_FLAGS = \$(FF77_FLAGS) -std=f2008
FFXX_OPT_FLAGS = -O2
C_FLAGS   = -fPIC -O2 -std=c99

AR       = ar
AR_FLAGS = -rvs

LINKER       = \$(FF90)
LINKER_FLAGS =

include \${PETSC_DIR}/lib/petsc/conf/variables
PETSC_INCLUDE_FLAGS=\${PETSC_CC_INCLUDES} -I\$(PETSC_DIR)
PETSC_LINKER_FLAGS=\${PETSC_LIB}

FF90_PRECISION_FLAGS = \$(FF90_INTEGER_PRECISION_FLAG)\$(FF90_REAL_PRECISION_FLAG)
CC_PRECISION_FLAGS   = \$(CC_INTEGER_PRECISION_FLAG) \$(CC_REAL_PRECISION_FLAG)

PYTHON = $PYTHON
PYTHON-CONFIG = ${PYTHON}-config
F2PY = f2py
CONFIGEOF

echo "  Written: config/config.mk"

# --- Step 2: Run patch script ---
echo ""
echo "[2/5] Patching ADflow source..."
export ADFLOW_SRC="$ADFLOW_ROOT/src"
$PYTHON "$ADFLOW_ROOT/patch_adflow_turb.py"

# --- Step 3: Compile ---
echo ""
echo "[3/5] Compiling ADflow (this may take several minutes)..."
cd "$ADFLOW_ROOT"
make clean 2>/dev/null || true
make

# --- Step 4: Setup Python path ---
echo ""
echo "[4/5] Setting up Python access..."

# Try pip install first, fall back to PYTHONPATH
if pip install -e "$ADFLOW_ROOT" --no-build-isolation --no-deps 2>/dev/null; then
    echo "  pip install -e . succeeded"
else
    echo "  pip install failed (no network?), using PYTHONPATH instead"
    echo "  Add to your environment:"
    echo "    export PYTHONPATH=$ADFLOW_ROOT:\$PYTHONPATH"
fi

# Copy ctypes interface to adflow package directory
cp "$ADFLOW_ROOT/adflow_turb_ctypes.py" "$ADFLOW_ROOT/adflow/adflow_turb_ctypes.py" 2>/dev/null || true

# --- Step 5: Verify ---
echo ""
echo "[5/5] Verifying installation..."

$PYTHON -c "
import sys
sys.path.insert(0, '$ADFLOW_ROOT')
from adflow_turb_ctypes import set_sa_constants, get_sa_constants, set_sa_defaults

set_sa_defaults()
c = get_sa_constants()
assert abs(c['cb1'] - 0.1355) < 1e-6, f'cb1 default wrong: {c[\"cb1\"]}'

set_sa_constants(0.5, 0.622, 2/3, 0.41, 7.1, 0.3, 2.0, 1.2, 0.5)
c = get_sa_constants()
assert abs(c['cb1'] - 0.5) < 1e-6, f'cb1 set failed: {c[\"cb1\"]}'

set_sa_defaults()
c = get_sa_constants()
assert abs(c['cb1'] - 0.1355) < 1e-6, f'cb1 reset failed: {c[\"cb1\"]}'

print('  ctypes interface: OK')
print('  SA read/write/reset: OK')
"

echo ""
echo "======================================================================"
echo "  Deployment complete!"
echo ""
echo "  Usage in Python scripts:"
echo "    from adflow_turb_ctypes import set_sa_constants, set_sst_constants"
echo "    set_sa_constants(cb1=0.2, cb2=0.622, sigma=2/3, kappa=0.41,"
echo "                     cv1=7.1, cw2=0.3, cw3=2.0, ct3=1.2, ct4=0.5)"
echo "======================================================================"
